### PR TITLE
Sphere random adj

### PR DESCRIPTION
**Pull request by NiklasKramer**
sloooooooooooow down random movement of spheres <3

### CODE REVIEW

**Comment by MalteMittrowann** [comment]
I like the slow movement of the randomDotsMovement and also the feel when dragging the dots. It feels bouncy and heavy but not draggy and too slow. This is good!

### There is an issue with switching tracks though:

When switching to a track that has the _RandomNotesFunction_ activated, the dots move very slowly to the position they where before and then move on from there.
When switching to a canvas that has this function **deactivated**, the dots move fastly, as I would expect them to do.

**Comment by SimonThormeyer** [comment]
> 
> 
> I like the slow movement of the randomDotsMovement and also the feel when dragging the dots. It feels bouncy and heavy but not draggy and too slow. This is good!
> ### There is an issue with switching tracks though:
> 
> When switching to a track that has the _RandomNotesFunction_ activated, the dots move very slowly to the position they where before and then move on from there.
> When switching to a canvas that has this function **deactivated**, the dots move fastly, as I would expect them to do.

will fix!

**Comment by MalteMittrowann** [comment]
### Another issue:

When deactivating the **randomDotsFunction** _while the dots are in their slooooooow movement_ they snap very fast to their destinated coordinates.

This is also strange behaviour....

**Comment by SimonThormeyer** [comment]
> 
> ### Another issue:
> 
> When deactivating the **randomDotsFunction** _while the dots are in their slooooooow movement_ they snap very fast to their destinated coordinates.
> 
> This is also strange behaviour....

Having an idea on how to fix this. Can you help testing this? :)

**Review by MalteMittrowann — APPROVED** [review]
The issues that @SimonThormeyer has fixed are fixed and work great. The dots move as expected.

It is still possible to provoke strange movement when going crazy with **starting and stopping** the _Random-Function_ and **switching** the _tracks_.
But nothing I have done has crashed the app, the bugs are not reproducible and only occur when abusing the buttons in a not useful way.
As a matter of facts, in my opinion, these issues are tolerable.

I would approve these changes because they change the feel of the app in a positive way.

-----

Also the cleanup is done nicely!

**Pull request merged**
