### PR TITLE
visual representation of navigation arrows for multitracking

### LINKED ISSUE #140: navigation to switch between canvas for multitracking (User Story  #139)
Description of the Ticket:

**Is part of story** #139 

ToDo's:
- [x] create arrows 
- [x] create placeholder for synthi name
- [x] create empty onClick functions on arrows (to be filled with functionality)

### PR DESCRIPTION
**Pull request by chanty1512**
navigation arrows (onClick action) and synthesizer name placeholder for multitracking without further functionality (only visual representation).

Note: possible number of loops has to be limited (in looper.js?, @NiklasKramer & @SimonThormeyer ?)

### CODE REVIEW

**Comment by MalteMittrowann** [comment]
Ich kriege diesen Fehler:

"
**Failed to compile**

./src/components/SaveProject.js
Module not found: Can't resolve 'axios' in 'C:\Users\Malte\Documents\Medieninformatik\5. Semester\Sourcecode\beuthSoundGroup\Frontend\src\components'
"

Was muss ich tun, um diesen Branch testen zu können?

**Comment by NiklasKramer** [comment]
yarn install

**Comment by SimonThormeyer** [comment]
> 
> 
> navigation arrows (onClick action) and synthesizer name placeholder for multitracking without further functionality (only visual representation).
> 
> Note: possible number of loops has to be limited (in looper.js?, @NiklasKramer & @SimonThormeyer ?)

I think loopers will have to be limited where they are created, which is in menu.js :) --> only create a new object if runningLoopers.size < limit (else show a little info-message about maximum amount of loopers)

**Comment by SimonThormeyer** [comment]
note: limiting loopers to be solved in a separate issue

**Review by SimonThormeyer — APPROVED** [review]

**Pull request merged**
